// Code generated by "stringer -type=TagCode"; DO NOT EDIT.

package swf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[End-0]
	_ = x[ShowFrame-1]
	_ = x[DefineShape-2]
	_ = x[PlaceObject-4]
	_ = x[RemoveObject-5]
	_ = x[DefineBits-6]
	_ = x[DefineButton-7]
	_ = x[JpegTables-8]
	_ = x[SetBackgroundColor-9]
	_ = x[DefineFont-10]
	_ = x[DefineText-11]
	_ = x[DoAction-12]
	_ = x[DefineFontInfo-13]
	_ = x[DefineSound-14]
	_ = x[StartSound-15]
	_ = x[DefineButtonSound-17]
	_ = x[SoundStreamHead-18]
	_ = x[SoundStreamBlock-19]
	_ = x[DefineBitsLossless-20]
	_ = x[DefineBitsJpeg2-21]
	_ = x[DefineShape2-22]
	_ = x[DefineButtonCxform-23]
	_ = x[Protect-24]
	_ = x[PlaceObject2-26]
	_ = x[RemoveObject2-28]
	_ = x[DefineShape3-32]
	_ = x[DefineText2-33]
	_ = x[DefineButton2-34]
	_ = x[DefineBitsJpeg3-35]
	_ = x[DefineBitsLossless2-36]
	_ = x[DefineEditText-37]
	_ = x[DefineSprite-39]
	_ = x[NameCharacter-40]
	_ = x[ProductInfo-41]
	_ = x[FrameLabel-43]
	_ = x[SoundStreamHead2-45]
	_ = x[DefineMorphShape-46]
	_ = x[DefineFont2-48]
	_ = x[ExportAssets-56]
	_ = x[ImportAssets-57]
	_ = x[EnableDebugger-58]
	_ = x[DoInitAction-59]
	_ = x[DefineVideoStream-60]
	_ = x[VideoFrame-61]
	_ = x[DefineFontInfo2-62]
	_ = x[DebugId-63]
	_ = x[EnableDebugger2-64]
	_ = x[ScriptLimits-65]
	_ = x[SetTabIndex-66]
	_ = x[FileAttributes-69]
	_ = x[PlaceObject3-70]
	_ = x[ImportAssets2-71]
	_ = x[DefineFontAlignZones-73]
	_ = x[CsmTextSettings-74]
	_ = x[DefineFont3-75]
	_ = x[SymbolClass-76]
	_ = x[Metadata-77]
	_ = x[DefineScalingGrid-78]
	_ = x[DoAbc-82]
	_ = x[DefineShape4-83]
	_ = x[DefineMorphShape2-84]
	_ = x[DefineSceneAndFrameLabelData-86]
	_ = x[DefineBinaryData-87]
	_ = x[DefineFontName-88]
	_ = x[StartSound2-89]
	_ = x[DefineBitsJpeg4-90]
	_ = x[DefineFont4-91]
	_ = x[EnableTelemetry-93]
	_ = x[PlaceObject4-94]
}

const _TagCode_name = "EndShowFrameDefineShapePlaceObjectRemoveObjectDefineBitsDefineButtonJpegTablesSetBackgroundColorDefineFontDefineTextDoActionDefineFontInfoDefineSoundStartSoundDefineButtonSoundSoundStreamHeadSoundStreamBlockDefineBitsLosslessDefineBitsJpeg2DefineShape2DefineButtonCxformProtectPlaceObject2RemoveObject2DefineShape3DefineText2DefineButton2DefineBitsJpeg3DefineBitsLossless2DefineEditTextDefineSpriteNameCharacterProductInfoFrameLabelSoundStreamHead2DefineMorphShapeDefineFont2ExportAssetsImportAssetsEnableDebuggerDoInitActionDefineVideoStreamVideoFrameDefineFontInfo2DebugIdEnableDebugger2ScriptLimitsSetTabIndexFileAttributesPlaceObject3ImportAssets2DefineFontAlignZonesCsmTextSettingsDefineFont3SymbolClassMetadataDefineScalingGridDoAbcDefineShape4DefineMorphShape2DefineSceneAndFrameLabelDataDefineBinaryDataDefineFontNameStartSound2DefineBitsJpeg4DefineFont4EnableTelemetryPlaceObject4"

var _TagCode_map = map[TagCode]string{
	0:  _TagCode_name[0:3],
	1:  _TagCode_name[3:12],
	2:  _TagCode_name[12:23],
	4:  _TagCode_name[23:34],
	5:  _TagCode_name[34:46],
	6:  _TagCode_name[46:56],
	7:  _TagCode_name[56:68],
	8:  _TagCode_name[68:78],
	9:  _TagCode_name[78:96],
	10: _TagCode_name[96:106],
	11: _TagCode_name[106:116],
	12: _TagCode_name[116:124],
	13: _TagCode_name[124:138],
	14: _TagCode_name[138:149],
	15: _TagCode_name[149:159],
	17: _TagCode_name[159:176],
	18: _TagCode_name[176:191],
	19: _TagCode_name[191:207],
	20: _TagCode_name[207:225],
	21: _TagCode_name[225:240],
	22: _TagCode_name[240:252],
	23: _TagCode_name[252:270],
	24: _TagCode_name[270:277],
	26: _TagCode_name[277:289],
	28: _TagCode_name[289:302],
	32: _TagCode_name[302:314],
	33: _TagCode_name[314:325],
	34: _TagCode_name[325:338],
	35: _TagCode_name[338:353],
	36: _TagCode_name[353:372],
	37: _TagCode_name[372:386],
	39: _TagCode_name[386:398],
	40: _TagCode_name[398:411],
	41: _TagCode_name[411:422],
	43: _TagCode_name[422:432],
	45: _TagCode_name[432:448],
	46: _TagCode_name[448:464],
	48: _TagCode_name[464:475],
	56: _TagCode_name[475:487],
	57: _TagCode_name[487:499],
	58: _TagCode_name[499:513],
	59: _TagCode_name[513:525],
	60: _TagCode_name[525:542],
	61: _TagCode_name[542:552],
	62: _TagCode_name[552:567],
	63: _TagCode_name[567:574],
	64: _TagCode_name[574:589],
	65: _TagCode_name[589:601],
	66: _TagCode_name[601:612],
	69: _TagCode_name[612:626],
	70: _TagCode_name[626:638],
	71: _TagCode_name[638:651],
	73: _TagCode_name[651:671],
	74: _TagCode_name[671:686],
	75: _TagCode_name[686:697],
	76: _TagCode_name[697:708],
	77: _TagCode_name[708:716],
	78: _TagCode_name[716:733],
	82: _TagCode_name[733:738],
	83: _TagCode_name[738:750],
	84: _TagCode_name[750:767],
	86: _TagCode_name[767:795],
	87: _TagCode_name[795:811],
	88: _TagCode_name[811:825],
	89: _TagCode_name[825:836],
	90: _TagCode_name[836:851],
	91: _TagCode_name[851:862],
	93: _TagCode_name[862:877],
	94: _TagCode_name[877:889],
}

func (i TagCode) String() string {
	if str, ok := _TagCode_map[i]; ok {
		return str
	}
	return "TagCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
