//go:generate stringer -type=TagCode
package swf

type TagCode uint16

const (
	EndCode                          TagCode = 0
	ShowFrameCode                    TagCode = 1
	DefineShapeCode                  TagCode = 2
	PlaceObjectCode                  TagCode = 4
	RemoveObjectCode                 TagCode = 5
	DefineBitsCode                   TagCode = 6
	DefineButtonCode                 TagCode = 7
	JpegTablesCode                   TagCode = 8
	SetBackgroundColorCode           TagCode = 9
	DefineFontCode                   TagCode = 10
	DefineTextCode                   TagCode = 11
	DoActionCode                     TagCode = 12
	DefineFontInfoCode               TagCode = 13
	DefineSoundCode                  TagCode = 14
	StartSoundCode                   TagCode = 15
	DefineButtonSoundCode            TagCode = 17
	SoundStreamHeadCode              TagCode = 18
	SoundStreamBlockCode             TagCode = 19
	DefineBitsLosslessCode           TagCode = 20
	DefineBitsJpeg2Code              TagCode = 21
	DefineShape2Code                 TagCode = 22
	DefineButtonCxformCode           TagCode = 23
	ProtectCode                      TagCode = 24
	PlaceObject2Code                 TagCode = 26
	RemoveObject2Code                TagCode = 28
	DefineShape3Code                 TagCode = 32
	DefineText2Code                  TagCode = 33
	DefineButton2Code                TagCode = 34
	DefineBitsJpeg3Code              TagCode = 35
	DefineBitsLossless2Code          TagCode = 36
	DefineEditTextCode               TagCode = 37
	DefineSpriteCode                 TagCode = 39
	NameCharacterCode                TagCode = 40
	ProductInfoCode                  TagCode = 41
	FrameLabelCode                   TagCode = 43
	SoundStreamHead2Code             TagCode = 45
	DefineMorphShapeCode             TagCode = 46
	DefineFont2Code                  TagCode = 48
	ExportAssetsCode                 TagCode = 56
	ImportAssetsCode                 TagCode = 57
	EnableDebuggerCode               TagCode = 58
	DoInitActionCode                 TagCode = 59
	DefineVideoStreamCode            TagCode = 60
	VideoFrameCode                   TagCode = 61
	DefineFontInfo2Code              TagCode = 62
	DebugIdCode                      TagCode = 63
	EnableDebugger2Code              TagCode = 64
	ScriptLimitsCode                 TagCode = 65
	SetTabIndexCode                  TagCode = 66
	FileAttributesCode               TagCode = 69
	PlaceObject3Code                 TagCode = 70
	ImportAssets2Code                TagCode = 71
	DefineFontAlignZonesCode         TagCode = 73
	CsmTextSettingsCode              TagCode = 74
	DefineFont3Code                  TagCode = 75
	SymbolClassCode                  TagCode = 76
	MetadataCode                     TagCode = 77
	DefineScalingGridCode            TagCode = 78
	DoAbcCode                        TagCode = 82
	DefineShape4Code                 TagCode = 83
	DefineMorphShape2Code            TagCode = 84
	DefineSceneAndFrameLabelDataCode TagCode = 86
	DefineBinaryDataCode             TagCode = 87
	DefineFontNameCode               TagCode = 88
	StartSound2Code                  TagCode = 89
	DefineBitsJpeg4Code              TagCode = 90
	DefineFont4Code                  TagCode = 91
	EnableTelemetryCode              TagCode = 93
	PlaceObject4Code                 TagCode = 94
	UnknownCode                      TagCode = 0xffff
)
