//go:generate stringer -type=TagCode
package swf

type TagCode uint16

const (
	End                          TagCode = 0
	ShowFrame                    TagCode = 1
	DefineShape                  TagCode = 2
	PlaceObject                  TagCode = 4
	RemoveObject                 TagCode = 5
	DefineBits                   TagCode = 6
	DefineButton                 TagCode = 7
	JpegTables                   TagCode = 8
	SetBackgroundColor           TagCode = 9
	DefineFont                   TagCode = 10
	DefineText                   TagCode = 11
	DoAction                     TagCode = 12
	DefineFontInfo               TagCode = 13
	DefineSound                  TagCode = 14
	StartSound                   TagCode = 15
	DefineButtonSound            TagCode = 17
	SoundStreamHead              TagCode = 18
	SoundStreamBlock             TagCode = 19
	DefineBitsLossless           TagCode = 20
	DefineBitsJpeg2              TagCode = 21
	DefineShape2                 TagCode = 22
	DefineButtonCxform           TagCode = 23
	Protect                      TagCode = 24
	PlaceObject2                 TagCode = 26
	RemoveObject2                TagCode = 28
	DefineShape3                 TagCode = 32
	DefineText2                  TagCode = 33
	DefineButton2                TagCode = 34
	DefineBitsJpeg3              TagCode = 35
	DefineBitsLossless2          TagCode = 36
	DefineEditText               TagCode = 37
	DefineSprite                 TagCode = 39
	NameCharacter                TagCode = 40
	ProductInfo                  TagCode = 41
	FrameLabel                   TagCode = 43
	SoundStreamHead2             TagCode = 45
	DefineMorphShape             TagCode = 46
	DefineFont2                  TagCode = 48
	ExportAssets                 TagCode = 56
	ImportAssets                 TagCode = 57
	EnableDebugger               TagCode = 58
	DoInitAction                 TagCode = 59
	DefineVideoStream            TagCode = 60
	VideoFrame                   TagCode = 61
	DefineFontInfo2              TagCode = 62
	DebugId                      TagCode = 63
	EnableDebugger2              TagCode = 64
	ScriptLimits                 TagCode = 65
	SetTabIndex                  TagCode = 66
	FileAttributes               TagCode = 69
	PlaceObject3                 TagCode = 70
	ImportAssets2                TagCode = 71
	DefineFontAlignZones         TagCode = 73
	CsmTextSettings              TagCode = 74
	DefineFont3                  TagCode = 75
	SymbolClass                  TagCode = 76
	Metadata                     TagCode = 77
	DefineScalingGrid            TagCode = 78
	DoAbc                        TagCode = 82
	DefineShape4                 TagCode = 83
	DefineMorphShape2            TagCode = 84
	DefineSceneAndFrameLabelData TagCode = 86
	DefineBinaryData             TagCode = 87
	DefineFontName               TagCode = 88
	StartSound2                  TagCode = 89
	DefineBitsJpeg4              TagCode = 90
	DefineFont4                  TagCode = 91
	EnableTelemetry              TagCode = 93
	PlaceObject4                 TagCode = 94
)
